### PR TITLE
add page icon & edit stuff

### PR DESCRIPTION
**Pull request by JaniduJ**

### CODE REVIEW

**Comment by davmillar** [comment]
Hey, I appreciate the edits, but what’s the logic behind changing the color of the info bubbles, adding those inline styles to one legend but not the rest, and what’s the story with the icon?

**Comment by JaniduJ** [comment]
Okay i will chnage it as seperate , and icon means web site page, you can add any picture for that
Sent from my Huawei Mobile

**Comment by davmillar** [comment]
Sorry I wasn't clear. I meant like why did you choose that specific icon, which doesn't look related to the website's topic at all and might not look super great scaled down.

**Comment by JaniduJ** [comment]
Ya that is only demo please choose any image you want ,I just suggest idea davmillarSent from my Huawei Mobile-------- Original Message --------Subject: Re: [davmillar/comedy] add page icon & edit stuff (#2)From: David Millar To: davmillar/comedy CC: Janidu Jayasanka ,State change Sorry I wasn't clear. I meant like why did you choose that specific icon, which doesn't look related to the website's topic at all and might not look super great scaled down.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/davmillar/comedy","title":"davmillar/comedy","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/davmillar/comedy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@davmillar in #2: Sorry I wasn't clear. I meant like why did you choose that specific icon, which doesn't look related to the website's topic at all and might not look super great scaled down."}],"action":{"name":"View Pull Request","url":"https://github.com/davmillar/comedy/pull/2#issuecomment-426670805"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/davmillar/comedy/pull/2#issuecomment-426670805",
"url": "https://github.com/davmillar/comedy/pull/2#issuecomment-426670805",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [davmillar/comedy] add page icon \u0026 edit stuff (#2)",
"sections": [
{
"text": "",
"activityTitle": "**David Millar**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@davmillar",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"davmillar/comedy\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"davmillar/comedy\",\n\"pullRequestId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/davmillar/comedy/pull/2#issuecomment-426670805"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 387074654\n}"
}
],
"themeColor": "26292E"
}
]

**Pull request closed without merging**
